linters:
  disable-all: true
  enable:
    - revive
    - staticcheck

linters-settings:
  revive:
    rules:
      - name: exported
        arguments:
          - "disableStutteringCheck"

issues:
  exclude-use-default: false
  exclude-files:
    - '.*\.pb\.go$'
